// SPDX-License-Identifier: MIT OR Apache-2.0
// GENERATED by scripts/gen-public-inputs.mjs from circuits/public_inputs.toml. Do not edit.
//
// The canonical public-input order is normative (§6, §19 C1): addresses left-padded uint160,
// everything else a big-endian uint256, each in one bytes32; points are two entries, x then y;
// the identity is (0, 0). The arrays below are exactly what DarkVault/DarkKeyRegistry pass to
// `IDarkVerifier.verify`, and `buildPublicInputs` is how the SDK re-derives them so it never has
// to trust a proof's own public inputs (§7 "the SDK re-derives the public inputs").
import { DarkError } from './errors.ts';
import type { CircuitId, Hex } from './prover.ts';

export const SPEC_VERSION = 'DARK-CB-1';

/** Wire public inputs per circuit, in order (§19 X2: wire count, not the VK's publicInputsSize). */
export const publicInputOrder = {
  dark_register: ['chain_id', 'registry', 'account', 'pk.x', 'pk.y'],
  dark_transfer: ['chain_id', 'vault', 'sender', 'recipient', 'sender_nonce', 'pk_s.x', 'pk_s.y', 'pk_r.x', 'pk_r.y', 'avail_c.x', 'avail_c.y', 'avail_d.x', 'avail_d.y', 'ct_c.x', 'ct_c.y', 'ct_ds.x', 'ct_ds.y', 'ct_dr.x', 'ct_dr.y', 'min_transfer', 'max_transfer'],
  dark_withdraw: ['chain_id', 'vault', 'account', 'to', 'nonce', 'pk.x', 'pk.y', 'avail_c.x', 'avail_c.y', 'avail_d.x', 'avail_d.y', 'amount'],
  dark_disclose_range: ['context_hash', 'pk.x', 'pk.y', 'c.x', 'c.y', 'd.x', 'd.y', 'lo', 'hi'],
} as const satisfies Record<CircuitId, readonly string[]>;

/** Which circuits have a deployed Solidity verifier. */
export const publicInputOnchain = {
  dark_register: true,
  dark_transfer: true,
  dark_withdraw: true,
  dark_disclose_range: false,
} as const satisfies Record<CircuitId, boolean>;

export const publicInputCount = Object.fromEntries(
  Object.entries(publicInputOrder).map(([k, v]) => [k, v.length]),
) as Record<CircuitId, number>;

/** A field, an address, or a point that supplies its `.x`/`.y` entries. */
export type PublicInputValue = bigint | number | string | { x: bigint | string; y: bigint | string };

const MAX_WORD = 1n << 256n;

function toWord(circuit: CircuitId, name: string, v: bigint | number | string): Hex {
  const n = typeof v === 'bigint' ? v : BigInt(v);
  if (n < 0n || n >= MAX_WORD) {
    throw new DarkError('PUBLIC_INPUT_MISMATCH', `${circuit}.${name} does not fit a bytes32`, { name, value: String(v) });
  }
  return `0x${n.toString(16).padStart(64, '0')}`;
}

/**
 * Build a circuit's `bytes32[]` exactly as the contracts pass it. Keys are the
 * `public_inputs.toml` names; a dotted name may instead come from an object under its
 * base name, so a witness record with `pk: {x, y}` supplies `pk.x` and `pk.y`.
 */
export function buildPublicInputs(
  circuit: CircuitId,
  fields: Record<string, unknown>,
): Hex[] {
  return publicInputOrder[circuit].map((name) => {
    let v = fields[name];
    const dot = name.indexOf('.');
    if (v === undefined && dot > 0) {
      const base = fields[name.slice(0, dot)];
      if (base && typeof base === 'object') v = (base as Record<string, unknown>)[name.slice(dot + 1)];
    }
    if (v === undefined || v === null || typeof v === 'object') {
      throw new DarkError('PUBLIC_INPUT_MISMATCH', `${circuit}: missing public input ${name}`, { name });
    }
    return toWord(circuit, name, v as bigint | number | string);
  });
}

/** Throws unless `got` matches `want` word for word. How a prover's output is checked. */
export function assertPublicInputsEqual(circuit: CircuitId, got: readonly string[], want: readonly Hex[]): void {
  const norm = (h: string) => h.toLowerCase();
  if (got.length !== want.length || got.some((g, i) => norm(g) !== norm(want[i]))) {
    throw new DarkError('PUBLIC_INPUT_MISMATCH', `${circuit}: prover public inputs differ from the SDK's`, {
      circuit,
      got: got.map(norm),
      want: want.map(norm),
    });
  }
}
